-- Proyecto Copec - esquema inicial para Supabase
-- Ejecutar completo en Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  name text not null,
  role text not null default 'admin' check (role in ('admin', 'inspector', 'dealer')),
  password_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.sessions (
  token_hash text primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.inspections (
  id bigint generated by default as identity primary key,
  numero text not null unique,
  vehicle_name text not null,
  plate text not null,
  price text not null,
  mileage text not null,
  owners text not null,
  score integer not null check (score between 0 and 100),
  items_checked integer not null check (items_checked >= 0),
  inspection_date text not null,
  status text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.stations (
  id bigint generated by default as identity primary key,
  name text not null,
  comuna text not null,
  direccion text not null,
  distancia text not null,
  horario text not null,
  cupos text not null,
  disponibilidad text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.inspection_files (
  id bigint generated by default as identity primary key,
  inspection_id bigint not null references public.inspections(id) on delete cascade,
  uploaded_by bigint references public.users(id) on delete set null,
  type text not null check (type in ('informe', 'video', 'foto', 'eco', 'scanner', 'documento')),
  title text not null,
  description text,
  stored_name text not null,
  original_name text not null,
  mime_type text not null,
  size bigint not null check (size >= 0),
  url text not null,
  created_at timestamptz not null default now()
);

create index if not exists sessions_user_id_idx on public.sessions(user_id);
create index if not exists sessions_expires_at_idx on public.sessions(expires_at);
create index if not exists inspection_files_inspection_id_idx on public.inspection_files(inspection_id);
create index if not exists inspection_files_created_at_idx on public.inspection_files(created_at desc);

insert into public.users (email, name, role, password_hash)
values (
  'admin@copec.cl',
  'Administrador Copec',
  'admin',
  crypt('Copec123!', gen_salt('bf'))
)
on conflict (email) do nothing;

insert into public.inspections (
  numero,
  vehicle_name,
  plate,
  price,
  mileage,
  owners,
  score,
  items_checked,
  inspection_date,
  status
)
values (
  'CL-2026-0515-4821',
  'Mazda CX-5 2.0 Skyactiv 2021',
  'LP-KT-58',
  '$18.990.000',
  '42.800 km',
  '1 dueño',
  87,
  98,
  '15 mayo 2026',
  'Aprobado Copec'
)
on conflict (numero) do nothing;

insert into public.stations (name, comuna, direccion, distancia, horario, cupos, disponibilidad)
values
  ('Copec Los Dominicos', 'Las Condes', 'Av. Padre Hurtado Sur 875', '2,4 km', 'Lun a sáb · 09:00 a 18:30', '3 cupos hoy', 'Disponible'),
  ('Copec Vitacura Kennedy', 'Vitacura', 'Av. Kennedy 5601', '4,1 km', 'Lun a vie · 08:30 a 18:00', 'Próximo cupo 10:30', 'Disponible'),
  ('Copec Príncipe de Gales', 'La Reina', 'Av. Príncipe de Gales 6850', '5,7 km', 'Lun a sáb · 09:30 a 17:30', '2 cupos mañana', 'Disponible'),
  ('Copec Manquehue Sur', 'Las Condes', 'Manquehue Sur 1230', '3,8 km', 'Lun a vie · 09:00 a 19:00', 'Agenda semanal', 'Alta demanda')
on conflict do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'inspection-files',
  'inspection-files',
  true,
  262144000,
  array[
    'application/pdf',
    'application/json',
    'image/jpeg',
    'image/png',
    'image/webp',
    'text/plain',
    'video/mp4',
    'video/quicktime',
    'video/webm'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

alter table public.users enable row level security;
alter table public.sessions enable row level security;
alter table public.inspections enable row level security;
alter table public.stations enable row level security;
alter table public.inspection_files enable row level security;

drop policy if exists "Public can read inspections" on public.inspections;
create policy "Public can read inspections"
on public.inspections
for select
using (true);

drop policy if exists "Public can read stations" on public.stations;
create policy "Public can read stations"
on public.stations
for select
using (true);

drop policy if exists "Public can read inspection files" on public.inspection_files;
create policy "Public can read inspection files"
on public.inspection_files
for select
using (true);

drop policy if exists "Authenticated can manage inspections" on public.inspections;
create policy "Authenticated can manage inspections"
on public.inspections
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can manage stations" on public.stations;
create policy "Authenticated can manage stations"
on public.stations
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can manage inspection files" on public.inspection_files;
create policy "Authenticated can manage inspection files"
on public.inspection_files
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Public can read inspection storage" on storage.objects;
create policy "Public can read inspection storage"
on storage.objects
for select
using (bucket_id = 'inspection-files');

drop policy if exists "Authenticated can upload inspection storage" on storage.objects;
create policy "Authenticated can upload inspection storage"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'inspection-files');

drop policy if exists "Authenticated can update inspection storage" on storage.objects;
create policy "Authenticated can update inspection storage"
on storage.objects
for update
to authenticated
using (bucket_id = 'inspection-files')
with check (bucket_id = 'inspection-files');

drop policy if exists "Authenticated can delete inspection storage" on storage.objects;
create policy "Authenticated can delete inspection storage"
on storage.objects
for delete
to authenticated
using (bucket_id = 'inspection-files');
